org: gonzalodst
service: api-web-scraping

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  region: us-east-1
  iam:
    role: arn:aws:iam::372738539467:role/LabRole
  environment:
    EARTHQUAKES_TABLE: !Ref TablaEarthquakes

functions:
  scrape_earthquakes:
    handler: handlers/scrape_earthquakes.lambda_handler
    package:
      include:
        - ./**
    events:
      - http:
          path: /earthquakes/scrape
          method: get
          cors: true
          integration: lambda
  
  get_earthquakes:
    handler: handlers/get_earthquakes.lambda_handler
    package:
      include:
        - ./**
    events:
      - http:
          path: /earthquakes
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TablaEarthquakes:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaEarthquakes
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: timestamp-index
            KeySchema:
              - AttributeName: timestamp
                KeyType: HASH
            Projection:
              ProjectionType: ALL